### ISSUE TITLE
People List widget permalinks

### ISSUE THREAD

**Issue by ryanlebreton-gmu** [jmacario-gmu/gmuj-wordpress-plugin-mason-custom-widgets#3]
@jmacario-gmu  - I came across an interesting issue while converting a site to the Mason theme. If a page has the same name as a person post, that page's permalink gets used in the people list widget instead of the People post's permalink. I haven't spent a lot of time investigating this, but I think it has to do with how the link is being generated in line 206 of gmuj_widget_people_list.php:

`echo'<a class="widget_gmuj_widget_display_list_item" href="'.get_permalink(get_page_by_path(get_post_field('post_name'))).'">';`

This isn't a set of circumstances that's likely to come up extremely often, but is there a reason not to get the permalink by post ID there instead?

**Comment by jmacario-gmu** [comment]
Oh that is very interesting. Good catch.
I'll have to look into it as well but, offhand, your suggested cause sounds plausible and your suggested solution sounds good. 
Actually that seems like a better method in general than was was done here. Pulling the permalink by post ID seems simpler and clearer.
Thanks!

**Comment by jmacario-gmu** [comment]
As you point out, the method used here to retrieve the permalink can be ambiguous, and is needlessly convoluted at best:

`get_permalink(get_page_by_path(get_post_field('post_name')))`

Unsurprisingly, the `get_page_by_path()` function defaults to returning a post object of post_type= 'page'. So in this case it returns the permalink for the page post and not the permalink for the person post for two posts with the same post_name. I'm a little surprised that it had been working at all, since the person posts have different post_type ('person').

Interestingly, this same method of retrieving a permalink is also used in the recent posts widget, but in that case it is moot because pages and posts of the same name can have the same permalink by default (so it's already ambiguous by the time it gets to this point), whereas pages and people of the same name can't have the same permalink (because people permalinks include '/person/' in the URL, at least the way we've registered the custom post type, which is typical). 

(Surprisingly WordPress will default to using the same slug for a post and a page with the same name. It only seems to notice the conflict and add the "-2", etc. when adding a second post of the same type as an existing post.)

In any event, your suggestion avoids this ambiguity when it arises and is just a simpler and clearer method of retrieving a permalink:

`get_permalink(get_post_field('ID'))`

However, there is an even shorter method. The `get_post_field()` function defaults to use the global post object (which is why we don't have to specify a post in the function call)> Then this post gets sent to the `get_permalink()` function. But the `get_permalink()` function will also default to use the global post object, so we can cut out the `get_post_field()` function too and just use:

`get_permalink()`

I have addressed this with new commit 3d34b26.
